services:
  postgres:
    image: postgres:16
    container_name: biblioteca-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: biblioteca_user
      POSTGRES_PASSWORD: root1234
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: