spring.application.name=biblioteca

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=biblioteca_user
spring.datasource.password=root1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

server.port=8080

security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration-minutes=60